{
 "title": "Grafana Dashboard",
 "description": "Grafana intrnal metrics dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(grafana_build_info)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptors Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Usage",
     "type": "graph",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]))",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  {
   "title": "Responce Codes and Logins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Response Statuses",
     "type": "graph",
     "description": "http response status",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grafana_api_response_status_total{instance=\"$instance\"}",
       "legendFormat": "API {{ code }}"
      },
      {
       "expr": "grafana_page_response_status_total{instance=\"$instance\"}",
       "legendFormat": "API {{ code }}"
      },
      {
       "expr": "grafana_proxy_response_status_total{instance=\"$instance\"}",
       "legendFormat": "API {{ code }}"
      }
     ]
    },
    {
     "title": "HTTP Req/Resp Details",
     "type": "graph",
     "description": "http request counter",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_request_total{instance=\"$instance\"}",
       "legendFormat": "{{handler}}-{{method}}-{{statuscode}}"
      }
     ]
    },
    {
     "title": "Login Counts",
     "type": "graph",
     "description": "api login counters",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grafana_api_login_post_total{instance=\"$instance\"}",
       "legendFormat": "POST"
      },
      {
       "expr": "grafana_api_login_oauth_total{instance=\"$instance\"}",
       "legendFormat": "OAuth"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataproxy Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataproxy Request Quantiles",
     "type": "graph",
     "description": "summary for dataproxy request duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=\"$instance\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=\"$instance\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dataproxy Request Avg [5 min]",
     "type": "graph",
     "description": "average dataproxy request duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{instance=\"$instance\"}[5m]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{instance=\"$instance\"}[5m])",
       "legendFormat": "Average Requests Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Get Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Get Duration Avg [5 min]",
     "type": "graph",
     "description": "average dashboard get duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{instance=\"$instance\"}[5m])/rate(grafana_api_dashboard_get_milliseconds_count{instance=\"$instance\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "Dashboard Get Duration Quantiles",
     "type": "graph",
     "description": "summary for dashboard get duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dashboard_get_milliseconds{instance=\"$instance\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_get_milliseconds{instance=\"$instance\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_get_milliseconds{instance=\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Save Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Save Duration Quantiles",
     "type": "graph",
     "description": "summary for dashboard save duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dashboard_save_milliseconds{instance=\"$instance\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_save_milliseconds{instance=\"$instance\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_save_milliseconds{instance=\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Save Duration Avg [5 min]",
     "type": "graph",
     "description": "average dashboard save duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{instance=\"$instance\"}[5m])/rate(grafana_api_dashboard_save_milliseconds_count{instance=\"$instance\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Search Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Search Duration Quantiles",
     "type": "graph",
     "description": "summary for dashboard search duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dashboard_search_milliseconds{instance=\"$instance\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_search_milliseconds{instance=\"$instance\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_search_milliseconds{instance=\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Search Duration Avg [5 min]",
     "type": "graph",
     "description": "average dashboard search duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{instance=\"$instance\"}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{instance=\"$instance\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  }
 ]
}