---
- hosts: all
  become: yes
  gather_facts: False
  roles:
    - pre_install
    - update_dn

- hosts: monitor_servers
  become: yes
  gather_facts: False
  roles:
    - prometheus_setup
    - alertmanager_setup

- hosts: all
  become: yes
  gather_facts: False
  roles:
    - node_exporter_setup

- hosts: storage_servers
  become: yes
  gather_facts: False
  roles:
    - victoria_metrics_setup