---
- name: Add_grafana_repository
  yum_repository:
    name: grafana
    baseurl: "{{ grafana.repo_base_url }}"
    repo_gpgcheck: yes
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ grafana.gpg_key_url }}"
    sslverify: yes
    sslcacert: "{{ grafana.sslcacert_path }}"

- name: Install_Grafana_Package
  yum:
    name: grafana
    state: present

- name: Change_permission_on_Grfana_configuration_directory_and_files
  file:
    path: "{{ grafana.configuration_path }}"
    recurse: yes
    mode: o+rw





