---
- name: Get_prometheus_distrib
  get_url:
    url: "{{ prometheus_arch.url }}{{ prometheus_arch.distrib }}"
    dest: "{{ path.tmp }}"
    owner: "{{ user.owner }}"
    group: "{{ user.group }}"
    mode: '0770'
    checksum: "{{ prometheus_arch.checksum }}"

- name: UnArchiv_prometheus_distrib
  unarchive:
    src: "{{ path.tmp }}"
    dest: "{{ prometheus_app_dir }}"
    remote_src: yes

- name: Delete_tmp_file_archive
  file:
    path: "{{ path.tmp }}/{{ prometheus_arch.distrib }}"
    state: absent

- name: Create_service_user_for_prometheus
  user:
    name: "{{ prometheus.service.user }}"
    shell: "{{ prometheus.service.shell }}"
    group: "{{ prometheus.service.group }}"
    create_home: no

- name: Create_DB_directory
  file:
    path: "{{ prometheus.db_dir }}"
    owner: "{{ prometheus.service.user }}"
    group: "{{ prometheus.service.group }}"
    recurse: yes

- name: Create_group_prometheus-sys
  group:
    name: "{{ prometheus.sys-group }}"
    state: present

- name: Add_users_vagrant and_prometheus_in_group_prometheus-sys
  user:
    name: "{{ item }}"
    groups: "{{ prometheus.sys-group}}"
    append: yes
  with_items:
    - "{{ user.owner }}"
    - "{{ prometheus.service.user }}"

- name: Create_lib_dir
  file:
    path: "{{ prometheus.lib_dir }}"
    state: directory

- name: Create_conf_and_exec_dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.owner }}"
    group: "{{ prometheus.sys-group }}"
    mode: '775'
  with_items:
    - "{{ prometheus.conf_dir }}"
    - "{{ prometheus.exec_dir }}"

- name: Copy_files_prometheus_to_lib_catalog
  copy:
    src: "{{ prometheus_app_dir }}/console_libraries"
    dest: "{{ prometheus.lib_dir }}/"
    remote_src: yes

- name: Copy_files_prometheus_to_conf_catalog
  copy:
    src: "{{ prometheus_app_dir }}/{{ item }}"
    dest: "{{ prometheus.conf_dir }}"
    remote_src: yes
    owner: "{{ user.owner }}"
    group: "{{ prometheus.sys-group }}"
    mode: '775'
  with_items:
    - consoles
    - LICENCE
    - NOTICE
    - prometheus.yml

- name: Copy_files_prometheus_to_exec_dir
  copy:
    src: "{{ prometheus_app_dir }}/{{ item }}"
    dest: "{{ prometheus.exec_dir }}"
    remote_src: yes
    owner: "{{ user.owner }}"
    group: "{{ prometheus.sys-group }}"
    mode: '775'
  with_items:
    - prometheus
    - promtool
    - tsdb

- name: Copy_SystemD_unit_file_promethus
  copy:
    src: promethus.service
    dest: "{{ prometheus.unit_dir }}"
    owner: 'root'
    group: 'root'
    mode: '644'

- name: Copy_EnvironmentFile_promethus
  template:
    src: promethus-options.j2
    dest: "{{ prometheus.conf_dir }}/prometheus-options"
    owner: "{{ user.owner }}"
    group: "{{ promethues.sys-group }}"
    mode: '664'


