---
- name: Get_prometheus_distrib
  get_url:
    url: "{{ prometheus_arch.url }}{{ prometheus_arch.distrib }}"
    dest: "{{ path.tmp }}"
    owner: "{{ user.owner }}"
    group: "{{ user.group }}"
    mode: '0770'
    checksum: "{{ prometheus_arch.checksum }}"

- name: UnArchiv_prometheus_distrib
  unarchive:
    src: "{{ path.tmp }}"
    dest: "{{ prometheus_app_dir }}"
    remote_src: yes

- name: Delete_tmp_file_archive
  file:
    path: "{{ path.tmp }}/{{ prometheus_arch.distrib }}"
    state: absent

- name: Create_service_user_for_prometheus
  user:
    name: "{{ prometheus.service.user }}"
    shell: "{{ prometheus.service.shell }}"
    group: "{{ prometheus.service.group }}"
    create_home: no

- name: Create_DB_directory
  file:
    path: "{{ prometheus.db_dir }}"
    owner: "{{ prometheus.service.user }}"
    group: "{{ prometheus.service.group }}"
    recurse: yes


