- name: Get_ip-address_from_monitor_server
  block:
    setup:
    register





- name: Generate_/etc/hosts_file_and_apply_on_all_servers
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

