- name: Check_servers
  ping:
- name: Setup_hostname_for_monitoring_server
  hostname:
    name: "{{ host_name.monitor_name}}{{ domain_name }}"
  when: ansible_host == "mon"
- name: Setup_hostname_for_client_server
  hostname:
    name: "{{ host_name.client_name}}{{ domain_name }}"
  when: ansible_host == "cli"
- name: Setup_hostname_for_storage_server
  hostname:
    name: "{{ host_name.storage_name}}{{ domain_name }}"
  when: ansible_host == "stor"
- name: Create_directory_for_apps
  file:
    path: {{ path.apps }}
    owner: {{ user.owner }}
    group: {{ user.group }}
    mode: '770'
- name: Create_directory_for_data
  file:
    path: {{ path.data }}
    owner: {{ user.owner }}
    group: {{ user.group }}
    mode: '770'