- name: Check_servers
  ping:

- name: Configure_monitor_server
  block:

    - name: Setup_hostname_for_monitor_server
      hostname:
        name: "{{ host_name.monitor_name}}{{ domain_name }}"

    - name: Create_data_directory_on_monitor_server
      file:
        path: "{{ path.data }}"
        owner: "{{ user.owner }}"
        group: "{{ user.group }}"
        mode: '0770'
        state: directory

  when: server_role == 'monitor_server'

- name: Configure_storage_server
  block:

    - name: Setup_hostname_for_storage_server
      hostname:
        name: "{{ host_name.storage_name}}{{ domain_name }}"

    - name: Create_data_directory_on_storage_server
      file:
        path: "{{ path.data }}"
        owner: "{{ user.owner }}"
        group: "{{ user.group }}"
        mode: '0770'
        state: directory

  when: server_role == 'storage_server'

- name: Configure_client_server
  block:

    - name: Setup_hostname_for_client_server
      hostname:
        name: "{{ host_name.client_name}}{{ domain_name }}"

  when: server_role == 'client_server'

- name: Install_base_support_packages
  yum:
    name: ['vim', 'tree', 'htop', 'nc', 'mc', 'wget', 'curl']
    state: present

- name: Upgrade_all_packages_and_os
  yum:
    name: '*'
    state: latest
  notify:
    - Reboot_all_servers








