- name: Check_servers
  ping:

- name: Configure_monitor_server
  block:

    - name: Setup_hostname_for_monitor_server
      hostname:
        name: "{{ host_name.monitor_name}}{{ domain_name }}"

    - name: Create_apps_and_data_directory_on_monitor_server
      file:
        path: "{{ item }}"
        owner: "{{ user.owner }}"
        group: "{{ user.group }}"
        mode: '0770'
        state: directory
      with_items:
        - "{{ path.apps }}"
        - "{{ path.data }}"

  when: server_role == 'monitor_server'

- name: Configure_storage_server
  block:

    - name: Setup_hostname_for_storage_server
      hostname:
        name: "{{ host_name.storage_name}}{{ domain_name }}"

    - name: Create_apps_and_data_directory_on_storage_server
      file:
        path: "{{ item }}"
        owner: "{{ user.owner }}"
        group: "{{ user.group }}"
        mode: '0770'
        state: directory
      with_items:
        - "{{ path.apps }}"
        - "{{ path.data }}"

  when: server_role == 'storage_server'

- name: Configure_client_server
  block:

    - name: Setup_hostname_for_client_server
      hostname:
        name: "{{ host_name.client_name}}{{ domain_name }}"

    - name: Create_directory_for_apps_onclient_server
      file:
        path: "{{ path.apps }}"
        owner: "{{ user.owner }}"
        group: "{{ user.group }}"
        mode: '0770'
        state: directory

  when: server_role == 'client_server'

- name: Install_base_support_packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tree
    - htop
    - nc
    - mc
    - wget
    - curl

- name: Upgrade_all_packages_and_os
  yum:
    name: '*'
    state: latest

- name: Reboot_all_servers
  reboot:
    reboot_timeout: '180'
    test_command: hostname

- name: Check_servers_after_reboot
  ping:





